credit_card_lake:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /app/data/lake.duckdb
      extensions:
        - parquet
        - httpfs
      settings:
        s3_region: us-east-1
