version: '3.8'

services:
  pipeline:
    build: .
    container_name: pipeline
    working_dir: /app
    network_mode: host
    volumes:
      - ./source:/app/source:ro
      - ./data:/app/data:rw
      - ./pipeline:/app/pipeline:rw
    env_file: .env
    environment:
      - DBT_PROFILES_DIR=/app/dbt
      - S3_BUCKET=cc-transaction-databricks-datalake-2026
      - AWS_DEFAULT_REGION=us-east-1
    command: python -m pipeline.pipeline
